version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 5
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 16.14.0
