name: Deploy

on:
  push:
    branches: 
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: npm ci
      run: |
        npm ci
      env:
        CI: true

    - name: npm run build-for-deploy
      run: |
        npm run build-for-deploy
      env:
        CI: true

    - name: Deploy
      uses: docker://peaceiris/gh-pages:00a0fa7ee8bd33aee5389fcee5eed89934afedef04c894283de2da307a793f92 # v2.5.1
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
      with:
        emptyCommits: false